### ISSUE TITLE
Fehler beim Erstellen vom Frontend

### ISSUE THREAD

**Issue by chico408** [dascr/dascr-board#1]
Hallo,
versuche gerade nach Doku das Projekt zum laufen zu bekommen. 
Beim erstellen von dem Frontend, bekomme ich folgenden Fehler.
![Unbenannt](https://user-images.githubusercontent.com/22233166/105631315-3a175600-5e4e-11eb-933a-b990cceec194.PNG)

Gruß

**Comment by patrickhener** [comment]
Ich hab ein update an der README gemacht. Auch wenn du die .env config so nicht nutzt brauchst du beide files, wenn du das Makefile nutzt. Deine Lösung wird sein `touch .env` im root directory. Dann gehts.

**Comment by chico408** [comment]
Jetzt bekomme ich diesen Fehler..., scheinbar gibt es kein install mehr?
![Unbenannt](https://user-images.githubusercontent.com/22233166/105631729-308eed80-5e50-11eb-9d4b-c15c007fd6b7.PNG)

**Comment by patrickhener** [comment]
Hast du node und yarn installiert?

**Comment by chico408** [comment]
Normal schon, bekomme aber als Ausgabe bei yarn --version, 0.32+git. Da stimmt vermutlich irgendetwas nicht.

**Comment by patrickhener** [comment]
Ja das hatte ich auch. Du brauchst ein aktuelleres yarn. Nicht das aus dem repo. Dann geht's

**Comment by chico408** [comment]
Ich habe jetzt schon alles probiert, und bleibe trotzdem weiterhin bei der Version. Wie hast du das Update denn gemacht?

**Comment by patrickhener** [comment]
https://linuxize.com/post/how-to-install-yarn-on-debian-10/ so oder so ähnlich war das.

**Comment by chico408** [comment]
Das hat geklappt. Danke
Brauche ich um von einem anderen Gerät daraufzugreifen zu können einen extra Webserver? Oder wird der Server selbst betrieben?

**Comment by patrickhener** [comment]
Du musst das Verzeichnis frontend/public mit nem Webserver zur Verfügung stellen. Siehe auch Absatz Deployment in der Readme.md

**Comment by chico408** [comment]
Kannst du das Vorgehen nochmal genauer Beschreiben? Also bei mir läuft jetzt alles soweit, ich bekomme allerdings kein Zugriff von einem anderen Gerät welches sich im selben Netzwerk befindet. Nur mit localhost.

**Comment by patrickhener** [comment]
Wie sehen denn deine beiden  .env Dateien aus? Wie startest du deinen Webserver? Mit so wenig Details kann ich dir nur schwer helfen.

**Comment by patrickhener** [comment]
Folgende Informationen wären also interessant @chico408 
```bash
** Aus dem Projektroot
cat .env
cat frontend/.env

** Webserverconfig
netstat -tulpen | grep 80
```

**Comment by chico408** [comment]
Guten Morgen,
hier meine beiden .env-Dateien:
![image](https://user-images.githubusercontent.com/22233166/105681470-7354d200-5ef1-11eb-8515-a2a0fcc53c47.png)

Hier meine Caddyfile:
`root * /home/[user]/dasrc-board/frontend/public
	encode gzip

	handle /api/* {
		reverse_proxy localhost:8000
	}

	handle /images/* {
		reverse_proxy localhost:8000
	}

	handle /uploads/* {
		reverse_proxy localhost:8000
	}

	handle /ws/* {
		reverse_proxy localhost:8000
	}

	handle {
		try_files {path} {file} /index.html
		file_server
	}

	header {
	# enable HSTS
	Strict-Transport-Security max-age=31536000;

	# disable clients from sniffing the media type
	X-Content-Type-Options nosniff

	# clickjacking protection
	X-Frame-Options DENY

	# keep referrer data off of HTTP connections
	Referrer-Policy no-referrer-when-downgrade
	}

	log {
		output file /var/log/caddy/example.com.access.log {
			roll_size 1gb
			roll_keep 5
			roll_keep_for 720h
		}
	}`
und dann starte ich mit 

`caddy run`

den Server

**Comment by patrickhener** [comment]
Okay und lauscht dein Webserver auch korrekt? `netstat -tulpen | grep 80` sollte dir dann 0.0.0.0:80 anzeigen.

**Comment by patrickhener** [comment]
Hab das grade mal auf nem pi nachgestellt. Bei mir hat das funktioniert. Hier sind mal meine files. Darauf achten, dass meiner ne andere ip hat als deiner:

*.env im root*
```
API_IP=0.0.0.0
API_PORT=8000
```

*.env in frontend*
```
API_URL=http://192.168.1.175:8000/api
API_BASE=http://192.168.1.175:8000/
WS_URL=ws://192.168.1.175:8000/ws
```

*Caddyfile /etc/caddy/Caddyfile*
```
:80

root * /home/patrick/dascr-board/frontend/public

encode gzip

handle /api/* {
	reverse_proxy localhost:8000
}

handle /images/* {
	reverse_proxy localhost:8000
}

handle /uploads/* {
	reverse_proxy localhost:8000
}

handle /ws/* {
	reverse_proxy localhost:8000
}

handle {
	try_files {path} {file} /index.html
	file_server
}

header {
# enable HSTS
Strict-Transport-Security max-age=31536000;

# disable clients from sniffing the media type
X-Content-Type-Options nosniff

# clickjacking protection
X-Frame-Options DENY

# keep referrer data off of HTTP connections
Referrer-Policy no-referrer-when-downgrade
}

log {
	output file /var/log/caddy/example.com.access.log {
		roll_size 1gb
		roll_keep 5
		roll_keep_for 720h
	}
}
```

**Comment by chico408** [comment]
Ich habe mein Problem gefunden..., ich hatte parallel einen Apache Server auf Port 80 laufen, deshalb habe ich kein Zugriff erhalten. Jetzt funktioniert es.  Bin auf die Schnittstelle zur Dartscheibe gespannt, ich werde dies mit einem Arduino über die Serielle Schnittstelle umsetzen, so wie du es bereits in deinem ersten Projekt gemacht hast.

**Comment by patrickhener** [comment]
Super. Resolved
