### ISSUE TITLE
Uncaught TypeError when loading CricketController after played X01-Game

### ISSUE THREAD

**Issue by RealNetcrusher** [dascr/dascr-board#20]
![image](https://user-images.githubusercontent.com/13837429/153614331-6c8612e2-7788-4ff7-bde6-923b975440b0.png)
Gleiches passiert auch beim Scoarboard.
![image](https://user-images.githubusercontent.com/13837429/153615373-40c0c299-4f5b-4df0-8ca3-2dad06f70665.png)

Der Fehler tritt auch bei Wechsel von anderen Spielen wie Split-Score nach Cricket auf.
Nach einem Reload der Seite ist der Controller wieder funktionsfähig.

```
yarn --version
1.22.17

node --version
v14.19.0

pnpm
Version 6.30.0

npm --version
6.14.16

gcc version 10.2.1 20210110 (Debian 10.2.1-6)

go version
go version go1.17.6 linux/arm64

git --version
git version 2.30.2

Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by patrickhener** [comment]
Fixed by pull request
