### ISSUE TITLE
make build Frontend

### ISSUE THREAD

**Issue by TimoboD** [dascr/dascr-board#25]
Hallo ich bekommen folgenden Fehler beim Erstellen des Frontends 

![grafik](https://user-images.githubusercontent.com/98890317/208300790-9b5bc407-887b-4e30-b7d3-81f1ac6486a0.png)

Versuche das ganze auf einem Raspberry Pi 4.
Woran könnte das liegen ?

go version go1.17 
node v19.2.0
npm 9.2.0
pnpm Version 7.18.2
git version 2.30.0

Gruß

**Comment by vainora** [comment]
I get the exact same error on my RaspPi 4b. Does anyone have an idea what this is or have you solved this already, @TimoboD

**Comment by patrickhener** [comment]
I do have the same error. SvelteKit is somewhat terrible when it comes to breaking changes. I will check on it and push a fixed version somewhat soonish.

**Comment by patrickhener** [comment]
I did check on the versions, which might solve this issue. Please do `git pull` and try if this fixes the issue.
Ich habe die versionen angehoben auf die aktuellen. Bitte einmal `git pull` machen und dann nochmals versuchen.

**Comment by vainora** [comment]
> I did check on the versions, which might solve this issue. Please do `git pull` and try if this fixes the issue. Ich habe die versionen angehoben auf die aktuellen. Bitte einmal `git pull` machen und dann nochmals versuchen.

It worked for me! Thanks a lot

**Comment by patrickhener** [comment]
As I assume it will for @TimoboD as well I will close the issue. If not please feel free to reopen.
