### ISSUE TITLE
docker: change backend-URL

### ISSUE THREAD

**Issue by asterix555** [dascr/dascr-board#28]
Hi,
after starting frontend and backend using "docker-compose up", the frontend is reachable but I received "Player was not created" error.
Short debugging showed that the frontend tries to connect to backend via "localhost:8000", while in my case localhost should be replaced with IP address of the server.

Is it possible to override the backend-url? I tried to set "VITE_API_BASE" environment variable in docker-compose-repo/local.yaml and also put the values in the .env file but wihout success,...

kind regards

**Comment by patrickhener** [comment]
I am checking the error and will return after analysis.

**Comment by patrickhener** [comment]
Okay analysis was quick. I did `docker-compose -f docker-compose-repo.yml up`. Afterwards I do have 2 ports exposed. Those are 8000 (this is the api) and 8080 (this is the frontend). So I browser to `http:// localhost:8080/player` and can add player just fine. This is done on the machine I am running the docker container on.

So just to clarify. Are you trying to connect to the scoreboard from another machine? If so I will need to expand my test setup here to see if I can reproduce the error.

**Comment by asterix555** [comment]
right, I installed it on a remote machine whereas I would like to access on various clients over network. I tried to tunnel the port 8000 via SSH to the client and it worked well.

But how can I tell the frontend not to connect to localhost but to a different IP?

**Comment by patrickhener** [comment]
Okay got it. So I will look into it and see if I can fix that or at least provide info how to rewrite Backend address. Thanks for clarifying.

**Comment by patrickhener** [comment]
So after looking into the issue and playing a bit with different approaches I am still unsure how to take it. Apparently there is: https://kit.svelte.dev/docs/modules#$env-dynamic-private and other variants of how to handle env in sveltekit. But no matter what I do, for Docker only those denoted in the frontend/Dockerfile get applied during build time. Whereas we would need a way to inject from docker-compose-local.yml file via Environment settings. So I need to investigate further to see if there is a good solution to it.

**Comment by patrickhener** [comment]
SvelteKit and reading env at runtime in a docker image seams to be quite complicated. At least I do not quite understand how to do it. Therefore I added a script to the Makefile, which pulls the customization from the .env file I use for running  it manually and overwrites it in the corresponding Dockerfile before building the docker image. So afterwards the ip address will be correct in all the calls as it is baked into the build Svelte bundle.

I think this is okay for now.
