### ISSUE TITLE
JavaScript out of Memory, run frontend

### ISSUE THREAD

**Issue by chico408** [dascr/dascr-board#7]
Ich erhalte folgenden Fehler, wenn ich versuche das frontend über 
`make run-dev-frontend` 
zu starten.

```
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
Aborted
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "rollup" exited with 134.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:86: run-dev-frontend] Error 1
```

Backend wird ganz normal gestartet und ich kann auch im Browser alles ordnungsgemäß bedienen.

**Comment by patrickhener** [comment]
Poste mal deine yarn und node Version. Mach auch mal nen git pull. Außerdem mal nen `make build-frontend` bevor du das nochmal ausführst.

**Comment by chico408** [comment]
Hier meine Versionen:
Yarn Version: 1.22.5
Node Verion: v14.15.4

Aber warum arbeitet die Website ohne Probleme, obwohl das Frontend nicht läuft, muss ich das nicht zwangsläufig starten?

**Comment by patrickhener** [comment]
Wenn die Seite noch verfügbar ist schätze ich dass dein Webserver den public folder noch zur Verfügung stellt. Wieso willst du das als frontend-dev laufen lassen? Planst du das weiterzuentwickeln? Stoppe mal deinen Webserver. Wenn du dann die Seite mit dem Browser nicht mehr erreichst versuchst du es nochmal mit make run-frontend-dev.

**Comment by chico408** [comment]
Ja ein paar Änderungen muss ich noch vornehmen, da das Scoreboard mit meiner Bildschirmauslösung nicht richtig dargestellt wird. 
Du hast recht, mein Frontend wurde durch den Webserver zur Verfügung gestellt. Zur Not kann ich das auch darüber anpassen, muss es halt dann immer neu builden oder?

**Comment by patrickhener** [comment]
Richtig. Aber dann kannst du ja von hier weiterarbeiten. Wenn du in CSS ne gute Einstellung für responsive Design findest nehme ich auch Pull-Requests an. Close
