### ISSUE TITLE
Finish-Vorschlag wird überschrieben

### ISSUE THREAD

**Issue by chico408** [dascr/dascr-board#8]
Sobald man im Finish-Bereich ist, wird korrekt ein möglicher Finish-Weg angezeigt. Wenn man dann allerdings wirft, verschwindet der Vorschlag und es erscheint "Round XX - Its players turn". 
Hier sollte der neue Finish-Weg angezeigt werden. #

**Comment by patrickhener** [comment]
Finishes werden nur bis einschl. 41 Restpunkte angezeigt. Kannst du mal 3 Finish Würfe pasten mit Zahl und Finish Vorschlag?

**Comment by chico408** [comment]
Ich habe jetzt zum Beispiel die 21 stehen, ein Vorschlag wäre z.B. die 1 und D10.

**Comment by patrickhener** [comment]
Wie gesagt. Unter 40 gibt's keine Vorschlägen mehr. Das Programm funktioniert in dem Fall wie gewollt.
